job('First-Maven-Project-Via-DSL'){
    description("First Maven Job Generated By The DSL On ${new Date()}, for testing dsl")
    scm{
        git("https://github.com/suyash-metha/MavenRepo.git","master")
    }
    triggers{
        scm('* * * * *')
    }
    steps{
        maven('clean package','JenkinDemo/pom.xml')
    }
    publishers{
        // archive the war file which is generated
        archiveArtifacts '**/*.jar'
    }
}