pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Java_Tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }    
            stage('Deploy In Staging Envirnoment'){
                steps{
                    build job:'Deploy_Application_Staging_Env'
                 }
             }
         stage('Deploy to Production'){
            steps{
                // timeout(time:5, unit:'DAYS'){
                //     input message:'Approve PRODUCTION Deployment?'
                // }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
    }   
}     