pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Java_Tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        stage('Depoly In Staging Envirnoment'){
            build job:'Deploy_Application_Staging_Env'
            }
        }
    }   
}     